name: Nx Distributed Tasks
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --no-tags --prune --depth=1 origin main
      - run: yarn install
      - run: yarn nx affected --target=test --base=origin/main --parallel
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --no-tags --prune --depth=1 origin main
      - run: yarn install
      - run: yarn nx affected --target=lint --base=origin/main --parallel
  build:
    runs-on: ubuntu-latest
    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true
      - run: git fetch --no-tags --prune --depth=1 origin main
      - run: |
          gcloud auth configure-docker -q
      - run: yarn install
      - run: yarn nx affected --base=origin/main --target=build --prod --parallel --dockerTag=gcr.io/${{ secrets.PROJECT_ID }}/ --hash=$(git rev-parse --short "$GITHUB_SHA") --branch=${{ env.BRANCH}}
