name: Nx Distributed Tasks
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --no-tags --prune --depth=1 origin main
      - run: npm install
      - run: yarn nx affected --target=test --base=origin/main --parallel
      - run: yarn nx affected --target=lint --base=origin/main --parallel
      - run: yarn nx affected --target=build --base=origin/main --prod --parallel
